// <auto-generated />
using System;
using Auth.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auth.Core.Migrations
{
    [DbContext(typeof(ImanageAuthDbContext))]
    partial class ImanageAuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auth.Core.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountType");

                    b.Property<string>("Address");

                    b.Property<string>("CAC");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("NIN");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PhoneNumber2");

                    b.Property<int>("Status");

                    b.Property<Guid>("User_Id");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Imanage.Shared.Models.ImanageRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("ImanageRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b6b6b0-0825-4975-a93d-df3dc86f8cc7"),
                            ConcurrencyStamp = "bb37771e9ab940ca999303cb06cbca98",
                            Name = "SYS_ADMIN",
                            NormalizedName = "SYS_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0718ddef-4067-4f29-aaa1-98c1548c1807"),
                            ConcurrencyStamp = "fbee38d182ed4da1bbf583ab80f7a603",
                            Name = "SUPER_ADMIN",
                            NormalizedName = "SUPER_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("8b93d395-a71a-4620-9352-5b9e6b3b6045"),
                            ConcurrencyStamp = "45c361c6fbde48f48461d1dbf89c1208",
                            Name = "LandLord",
                            NormalizedName = "LandLord"
                        },
                        new
                        {
                            Id = new Guid("c586e0ba-64a9-427b-8888-6f16755e5d9d"),
                            ConcurrencyStamp = "67234e38dfd04c23b87810ab4f7a42aa",
                            Name = "Estate_Manager",
                            NormalizedName = "Estate_Manager"
                        });
                });

            modelBuilder.Entity("Imanage.Shared.Models.ImanageRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.ToTable("ImanageRoleClaim");
                });

            modelBuilder.Entity("Imanage.Shared.Models.ImanageUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Activated");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<DateTime>("CreatedOnUtc");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(150);

                    b.Property<int>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastLoginDate");

                    b.Property<string>("LastName")
                        .HasMaxLength(150);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(150);

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("Unit");

                    b.Property<string>("UserName");

                    b.Property<int>("UserType");

                    b.Property<Guid?>("UserTypeId");

                    b.HasKey("Id");

                    b.ToTable("ImanageUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1989883f-4f99-43bf-a754-239bbbfec00b"),
                            AccessFailedCount = 0,
                            Activated = true,
                            ConcurrencyStamp = "52f105ed-35cc-4ee9-9444-bc8b74fe8d8f",
                            CreatedOnUtc = new DateTime(2020, 5, 27, 21, 9, 38, 265, DateTimeKind.Local).AddTicks(3497),
                            Email = "system@imanager.com",
                            EmailConfirmed = true,
                            FirstName = "Imanage",
                            Gender = 1,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2020, 5, 27, 21, 9, 38, 265, DateTimeKind.Local).AddTicks(6414),
                            LastName = "Estate Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "SYSTEM@IMANAGER.COM",
                            NormalizedUserName = "SYSTEM@IMANAGER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJC8yRZbtg7CPzw6nIjTZVn82MLUiS6wUGuyWx3Kc5vu7Ro5WmjTqIGNDCJlvjIE3A==",
                            PhoneNumber = "08062066851",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "99ae0c45-d682-4542-9ba7-1281e471916b",
                            TwoFactorEnabled = false,
                            UserName = "system@imanager.com",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba"),
                            AccessFailedCount = 0,
                            Activated = true,
                            ConcurrencyStamp = "7a6195d1-dc32-4ea8-8538-e859759adf41",
                            CreatedOnUtc = new DateTime(2020, 5, 27, 21, 9, 38, 281, DateTimeKind.Local).AddTicks(583),
                            Email = "superadmin@imanage.com",
                            EmailConfirmed = true,
                            FirstName = "Imanage",
                            Gender = 1,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2020, 5, 27, 21, 9, 38, 281, DateTimeKind.Local).AddTicks(600),
                            LastName = "Estate Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@IMANAGE.COM",
                            NormalizedUserName = "SUPERADMIN@IMANAGE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGS6VNr/qtIlSUq+G9mllAI38hYZcw5+S9aMp42oBm9T4vciHiq3GYf3etsCF4wmBw==",
                            PhoneNumber = "08062066851",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "016020e3-5c50-40b4-9e66-bba56c9f5bf2",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@imanage.com",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("5bcb4f11-3177-4905-bff8-fa645d0e055e"),
                            AccessFailedCount = 0,
                            Activated = true,
                            ConcurrencyStamp = "fe4c9851-4cee-4261-a285-2fe45a12a564",
                            CreatedOnUtc = new DateTime(2020, 5, 27, 21, 9, 38, 289, DateTimeKind.Local).AddTicks(2589),
                            Email = "adminuser@imanage.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            Gender = 1,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2020, 5, 27, 21, 9, 38, 289, DateTimeKind.Local).AddTicks(2594),
                            LastName = "adminUser",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINUSER@IMANAGE.COM",
                            NormalizedUserName = "ADMINUSER@IMANAGE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBzpCSgUb+oAlDUhPLQi63NffN/KOmrBwh7009EwvWmM7O47yI3K7RSpyTZ1xzPdhA==",
                            PhoneNumber = "08062066851",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7d728c76-1c51-491a-99db-bde6a5b0655a",
                            TwoFactorEnabled = false,
                            UserName = "adminuser@imanage.com",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a"),
                            AccessFailedCount = 0,
                            Activated = true,
                            ConcurrencyStamp = "5a7b9caa-d9d2-4ad7-abab-6ef8feee6c52",
                            CreatedOnUtc = new DateTime(2020, 5, 27, 21, 9, 38, 296, DateTimeKind.Local).AddTicks(8157),
                            Email = "admin@imanage.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            Gender = 1,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2020, 5, 27, 21, 9, 38, 296, DateTimeKind.Local).AddTicks(8163),
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@IMANAGE.COM",
                            NormalizedUserName = "ADMIN@IMANAGE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKt5HaJBfYvAQGw8lzfd60B9pdHmlyo5m9zdB56fX1Da7BwtzyIZoMBdUrTrgSLetA==",
                            PhoneNumber = "08062066851",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5725abea-38f8-45f7-a485-0805b59d078b",
                            TwoFactorEnabled = false,
                            UserName = "admin@imanage.com",
                            UserType = 2
                        });
                });

            modelBuilder.Entity("Imanage.Shared.Models.ImanageUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ImanageUserClaim");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Permission",
                            ClaimValue = "LANDLORD_PERM",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Permission",
                            ClaimValue = "GENERAL_INFO",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Permission",
                            ClaimValue = "ESTATE_MANAGER_PERM",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "Permission",
                            ClaimValue = "SYSTEM_VALIDATION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEWER",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Permission",
                            ClaimValue = "SEARCH",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_VIEW",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_BULK_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_VIEW",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_BULK_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEWER",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEW_ACTIONS",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEWER",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEW_DETAILS",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Permission",
                            ClaimValue = "NAV_INFO",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Permission",
                            ClaimValue = "SYSTEM_VALIDATION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "Permission",
                            ClaimValue = "REQUEST_ID",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Permission",
                            ClaimValue = "GENERAL_INFO",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "Permission",
                            ClaimValue = "VIEW_APPROVALS",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "Permission",
                            ClaimValue = "SEARCH",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_VIEW",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_ACTION",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_BULK_ACTION",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_VIEW",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_ACTION",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_BULK_ACTION",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEWER",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEW_ACTIONS",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEWER",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEW_DETAILS",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "Permission",
                            ClaimValue = "NAV_INFO",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "Permission",
                            ClaimValue = "SYSTEM_VALIDATION",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "Permission",
                            ClaimValue = "REQUEST_ID",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "Permission",
                            ClaimValue = "GENERAL_INFO",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "Permission",
                            ClaimValue = "VIEW_APPROVALS",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "Permission",
                            ClaimValue = "SYS_ADMIN_PERM",
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "Permission",
                            ClaimValue = "LANDLORD_PERM",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "Permission",
                            ClaimValue = "GENERAL_INFO",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "Permission",
                            ClaimValue = "ESTATE_MANAGER_PERM",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "Permission",
                            ClaimValue = "SYSTEM_VALIDATION",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEWER",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "Permission",
                            ClaimValue = "SEARCH",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_VIEW",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 46,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_ACTION",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 47,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_BULK_ACTION",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 48,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_VIEW",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 49,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_ACTION",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_BULK_ACTION",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEWER",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEW_ACTIONS",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEWER",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEW_DETAILS",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "Permission",
                            ClaimValue = "NAV_INFO",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "Permission",
                            ClaimValue = "SYSTEM_VALIDATION",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "Permission",
                            ClaimValue = "REQUEST_ID",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "Permission",
                            ClaimValue = "GENERAL_INFO",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "Permission",
                            ClaimValue = "VIEW_APPROVALS",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "Permission",
                            ClaimValue = "SUPER_ADMIN_PERM",
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba")
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "Permission",
                            ClaimValue = "ESTATE_MANAGER_PERM",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "Permission",
                            ClaimValue = "ESTATE_MANAGER_PERM",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "Permission",
                            ClaimValue = "SEARCH",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 64,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_VIEW",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 65,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 66,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_BULK_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 67,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_VIEW",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 68,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 69,
                            ClaimType = "Permission",
                            ClaimValue = "TABLE_2_BULK_ACTION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 70,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEWER",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 71,
                            ClaimType = "Permission",
                            ClaimValue = "DOCUMENT_VIEW_ACTIONS",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 72,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEWER",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 73,
                            ClaimType = "Permission",
                            ClaimValue = "DASHBOARD_VIEW_DETAILS",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 74,
                            ClaimType = "Permission",
                            ClaimValue = "NAV_INFO",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 75,
                            ClaimType = "Permission",
                            ClaimValue = "SYSTEM_VALIDATION",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 76,
                            ClaimType = "Permission",
                            ClaimValue = "REQUEST_ID",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 77,
                            ClaimType = "Permission",
                            ClaimValue = "GENERAL_INFO",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        },
                        new
                        {
                            Id = 78,
                            ClaimType = "Permission",
                            ClaimValue = "VIEW_APPROVALS",
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216")
                        });
                });

            modelBuilder.Entity("Imanage.Shared.Models.ImanageUserLogin", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasAlternateKey("Id");

                    b.ToTable("ImanageUserLogin");
                });

            modelBuilder.Entity("Imanage.Shared.Models.ImanageUserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("ImanageUserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a"),
                            RoleId = new Guid("a1b6b6b0-0825-4975-a93d-df3dc86f8cc7")
                        },
                        new
                        {
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba"),
                            RoleId = new Guid("0718ddef-4067-4f29-aaa1-98c1548c1807")
                        },
                        new
                        {
                            UserId = new Guid("129712e3-9214-4dd3-9c03-cfc4eb9ba979"),
                            RoleId = new Guid("880fd08d-044c-4068-b4e4-84c970344b3a")
                        },
                        new
                        {
                            UserId = new Guid("3d26739c-e070-4e99-8844-6a2e4c2bc216"),
                            RoleId = new Guid("c586e0ba-64a9-427b-8888-6f16755e5d9d")
                        },
                        new
                        {
                            UserId = new Guid("6ff03683-f832-4288-97b3-a79be8c6549c"),
                            RoleId = new Guid("8b93d395-a71a-4620-9352-5b9e6b3b6045")
                        },
                        new
                        {
                            UserId = new Guid("30349956-8a58-40e2-a06e-72073e1b0174"),
                            RoleId = new Guid("16d9503e-5322-4126-90ef-34eecf3d5a46")
                        });
                });

            modelBuilder.Entity("Imanage.Shared.Models.ImanageUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId");

                    b.ToTable("ImanageUserToken");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ClientSecret");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("ConsentType");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Permissions");

                    b.Property<string>("PostLogoutRedirectUris");

                    b.Property<string>("Properties");

                    b.Property<string>("RedirectUris");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("Properties");

                    b.Property<string>("Scopes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Properties");

                    b.Property<string>("Resources");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("AuthorizationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset?>("CreationDate");

                    b.Property<DateTimeOffset?>("ExpirationDate");

                    b.Property<string>("Payload");

                    b.Property<string>("Properties");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("[ReferenceId] IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens");
                });

            modelBuilder.Entity("Auth.Core.Models.Account", b =>
                {
                    b.HasOne("Imanage.Shared.Models.ImanageUser", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");
                });
#pragma warning restore 612, 618
        }
    }
}
